version: '3.4'
volumes:
  chain-data:

services:
  chain:
    image: poco-chaintest:5.3.0-token-parity
    container_name: chain
    volumes : 
    - chain-data:/iexec-poco/testchains/openethereum/chain-data
    ports:
      - 8545:8545
      - 8546:8546